# Generated by Django 4.2.3 on 2023-07-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('occupation', models.CharField(max_length=64)),
                ('date_occupation', models.DateTimeField(auto_now=True)),
                ('department', models.CharField()),
                ('other_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.info')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.BinaryField()),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('xlsx', 'Xlsx'), ('docx', 'Docx')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.info')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=None, max_length=64, null=True)),
                ('column', models.CharField(max_length=64)),
                ('key', models.CharField(default=None, max_length=64, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template')),
            ],
        ),
    ]
